# Generated by Django 5.0.9 on 2024-12-02 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('notified_email_to', models.EmailField(max_length=254)),
                ('notified_email_cc', models.EmailField(max_length=254)),
                ('notified_email_bcc', models.EmailField(max_length=254)),
                ('dept', models.CharField(choices=[('IT', 'IT'), ('HR', 'HR')], max_length=50)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], max_length=10)),
                ('corporate_sales_manager', models.CharField(choices=[('john_doe', 'John Doe'), ('jamie_vardy', 'Jamie Vardy')], max_length=50)),
                ('authorized_person', models.CharField(max_length=100)),
                ('authorized_person_mobile', models.CharField(max_length=20)),
                ('authorized_person_email', models.EmailField(max_length=254)),
                ('type', models.CharField(choices=[('customer', 'Customer'), ('none', 'None')], max_length=10)),
                ('industry', models.CharField(choices=[('tech', 'Technology'), ('finance', 'Finance'), ('healthcare', 'Healthcare')], max_length=20)),
                ('created_by', models.CharField(max_length=100)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
