# Generated by Django 5.0.9 on 2024-12-10 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='dept',
        ),
        migrations.AddField(
            model_name='company',
            name='siem_password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='siem_product',
            field=models.CharField(blank=True, choices=[('trellix_esm', 'Trellix ESM'), ('ibm', 'IBM')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='siem_username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
